### ISSUE TITLE
Heroku hangs

### ISSUE THREAD

**Issue by mykewould** [cknadler/git-feats#16]
I'm assuming gitfeats is running on the free heroku. 

Heroku will store unvisited sites and then hang when someone attempts to hit them for the first time. The problem is that when I go to issue a git command the api upload portion will hang for awhile, and block me from my work. 

I think the solution here may be a thread spawn to keep the IO from blocking.

**Comment by cknadler** [comment]
Agreed. I'm also trying to get sponsored by either Heroku, or another hosting company, which will fix part of the problem. Spawning a thread should happen either way though. 

This is what I'm thinking:
- when the user gets a feat while using git
  - spawn a new thread
  - post data to gitfeats.com
- when the user manually updates their feats
  - block and post data, display response from server

If the user is posting data to gitfeats.com, the site should respond with error messages, like user not found, bad key, etc. I dont know how we would display these to the user if we are doing the request on another thread. That's fine though. When the user manually updates the feats, I think git-feats should block, send the request and then display the response, so that the user knows if everything is working and if not, what is going wrong.

**Comment by cknadler** [comment]
I just finished the gitfeats.com api. I'm gonna start working on the gem's requests to it using [faraday](https://github.com/technoweenie/faraday).

The api: https://github.com/cknadler/gitfeats.com/issues/20

**Comment by cknadler** [comment]
It turns out this isn't as simple as I initially thought.

With my previous solution, all of the faraday request business would be handled on a separate thread from the actual git command. The problem is that, to execute the git command, I'm calling `exec` which destroys the current process and all associated threads. 

I'm not exactly sure how to go about doing this another way but here are some ideas:
- make the request to gitfeats.com a new (background?) process
- do the request on a separate thread and wait until it is finished to `exec`

The first solution is the only way I can think of that we are going to get executing to move any faster.

**Comment by cknadler** [comment]
Got it, this works:

``` ruby
#!/usr/bin/env ruby

require 'faraday'

URL = 'http://localhost:3000'

job = fork do
  conn = Faraday.new(:url => URL) do |faraday|
    faraday.request :url_encoded
    faraday.adapter Faraday.default_adapter
  end

  response = conn.post do |req|
    req.url '/api/feats'
    req.headers['Content-Type'] = 'application/json'
    req.body = '{"username": "name", "key": "abc", "history": { "commit": 1 }}'
  end
end

Process.detach(job)

arg = ["git", "status"]

exec(*arg)
```

**Comment by mykewould** [comment]
Looks good!
